import type { InvestigatorSignature } from "arkham-investigator-data";

export const createFallbackInvestigator = (
	data: Partial<InvestigatorSignature> = {},
): InvestigatorSignature => ({
	id: "fallback",
	name: "fallback",
	subname: "fallback",
	text: "",
	flavor: "",
	traits: "",
	gender: "non-binary",
	code: "fallback",
	faction_code: "neutral",
	tokens: [],
	tokens_reference: [],
	cycle: {
		locale: "en",
		code: "zinv",
		name: "fallback",
		position: 0,
		icon: "investigator",
	},
	pack: {
		locale: "en",
		code: "zinv",
		name: "fallback",
		position: 0,
		icon: "investigator",
	},
	canonical: false,
	custom: true,
	official: false,
	linked_code: "fallback",
	alternate_of_code: "fallback",
	type: "default",
	locale: "en",
	icon: "investigator",
	image: {
		id: "fallback",
		width: 0,
		height: 0,
		face: {
			width: 0,
			height: 0,
			left: 0,
			top: 0,
		},
	},
	sanity: 0,
	health: 0,
	skill_agility: 0,
	skill_combat: 0,
	skill_intellect: 0,
	skill_willpower: 0,
	taboo: false,
	taboo_set: null,
	taboo_original_text: null,
	taboo_text_change: null,
	spoiler: false,
	...data,
});
